#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Defining lists and tuples."""

ELEMENTS = (None, 'Hydrogen', 'Helium', 'Lithium', 'Beryllium', 'Boron',
            'Carbon'
            )
OPERATIONS_ORDER = ['Parentheses', 'Exponents', 'Multiplication', 'Division',
                    'Addition', 'Subtraction'
                    ]
